stepnames:
  setup_references: 000_setup_references
  augustus: 005_augustus

dirs:
  prefix: "/vol/jlab/Algorithms/PhyloFiller/"
  intermediate: "Intermediate/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"
  references: "References/"

projects:
  fungi:
    assembly_prefix: /Daten/PhyloFiller/Input/LCB-Genomes/
    fp_metadata: data/projects/fungi.tsv
