name: integration tests & code style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/mamba env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        $CONDA/bin/flake8 phylofiller/
    - name: run python tests
      run: |
        $CONDA/bin/nosetests phylofiller --with-doctest --with-coverage
    - name: convert coverage
      run: |
        $CONDA/bin/coverage lcov
    - name: send coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"
