name: integration tests & code style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        # This uses *miniforge*, rather than *minicond*. The primary difference is that
        # the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far less error
        # prone than conda while being completely compatible with the conda CLI
        use-mamba: true
        mamba-version: "*"
    - name: Install conda packages
      # The `-l` is needed so conda environment activation works correctly
      shell: bash -l {0}
      run: |
                mamba install -c conda-forge numpy scipy matplotlib

    # - name: Install dependencies
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     $CONDA/bin/conda env update --file environment.yml --name base
    # - name: Lint with flake8
    #   run: |
    #     $CONDA/bin/flake8 phylofiller/
    # - name: run python tests
    #   run: |
    #     $CONDA/bin/nosetests phylofiller --with-doctest --with-coverage
    # - name: convert coverage
    #   run: |
    #     $CONDA/bin/coverage lcov
    # - name: send coverage report
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: "coverage.lcov"
